[package]
name = "depencency-injection-rs"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
parking_lot = "0.12.5"
tokio = { version = "1.48.0", features = ["rt", "macros"] }
